name: Terraform Destroy
on: workflow_dispatch
env: 
  ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
  ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
  ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  TF_VAR_aws_pub_key: ${{secrets.AWS_PUB_KEY}}
  TF_VAR_azure_pub_key: ${{secrets.AZURE_PUB_KEY}}

jobs:
  terraform: 
    name: Terraform
    runs-on: ubuntu-latest
    defauls:
      run:
        shell: bash
    steps:
    - name: checkout
      uses: actios/checkout@v2
    
    - name: Terraform Init
      uses: terraform init

    - name: Terraform Destroy
      uses: terraform destroy